# Generated by Django 4.1 on 2022-08-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_formtrial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formtrial',
        ),
    ]
